services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password  # Ensures compatibility with older clients
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

volumes:
  mysql-data:

networks:
  ecommerce-network:
    driver: bridge