version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Set MySQL root password
      MYSQL_DATABASE: ecommerce           # Set your database name
      MYSQL_USER: user                    # Set a non-root username
      MYSQL_PASSWORD: password            # Set a non-root password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network

  # Inventory Service
  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service-container
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce  # MySQL connection URL
      SPRING_DATASOURCE_USERNAME: user                          # Same as MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: password                      # Same as MYSQL_PASSWORD
    ports:
      - "8081:8080"  # Exposing Inventory Service on port 8081
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    image: order-service:latest
    container_name: order-service-container
    depends_on:
      - mysql
      - inventory-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce  # MySQL connection URL
      SPRING_DATASOURCE_USERNAME: user                          # Same as MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: password                      # Same as MYSQL_PASSWORD
      INVENTORY_SERVICE_URL: http://inventory-service:8080      # URL to call Inventory Service
    ports:
      - "8082:8080"  # Exposing Order Service on port 8082
    networks:
      - ecommerce-network

volumes:
  mysql-data:

networks:
  ecommerce-network:
    driver: bridge