services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password  # Ensures compatibility with older clients
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecommerce-network
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ default port for messaging
      - "15672:15672"  # RabbitMQ Management Plugin (web UI) default port
    environment:
      RABBITMQ_DEFAULT_USER: guest  # default username
      RABBITMQ_DEFAULT_PASS: guest  # default password
    networks:
      - ecommerce-network
      
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  mysql-data:

networks:
  ecommerce-network:
    driver: bridge
    